<a href="https://colab.research.google.com/github/NayashaPrakash/AirQualityPrediction/blob/main/data_processing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import numpy as np

# Make numpy values easier to read.
np.set_printoptions(precision=3, suppress=True)

import tensorflow as tf
from tensorflow.keras import layers

In [4]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import r2_score, mean_squared_error, mean_absolute_error

raw_file_path = 'air_raw_data'
input_data = pd.read_csv(raw_file_path, parse_dates=['timestamp'])

input_data
# input_data.to_csv('/content/input_data.csv')

# print(input_data)

,timestamp,device_id,latitude,longitude,temperature,humidity,pm10,pm2_5
0,2023-01-05 02:29:00,3424,20.2392,85.7671,18.4,0,158.00,117.00
1,2023-01-05 15:34:00,3424,20.2392,85.7671,21.9,a,143.00,106.00
2,2023-01-05 17:10:00,3424,20.2392,85.7671,20.9,80.1,123.00,91.00
3,2023-01-12 19:40:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
4,2023-01-12 19:46:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
5,2023-01-15 06:18:00,3424,20.2392,85.7671,28.6,73.1,59.00,44.00
6,2023-01-17 04:13:00,3424,20.2392,85.7671,24.4,132,98.00,NaN
7,2023-01-17 07:27:00,3424,20.2392,85.7671,29.1,81.5,66.00,49.00
8,2023-01-26 03:32:00,3424,20.2392,85.7671,24,85.7,82.00,61.00
9,2023-01-26 11:03:00,3424,20.2392,85.7671,31.5,46.5,48.00,36.00
10,2023-02-01 01:23:00,3424,20.2392,85.7671,22.8,85.4,91.00,68.00
11,2023-03-08 22:32:00,3424,20.2392,85.7671,29.64,53.37,114.00,108.00
12,2023-03-10 05:29:00,3424,20.2392,85.7671,33.59,38.53,152.00,144.00
13,2023-07-25 13:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
14,2023-08-24 23:34:00,3424,20.2392,85.7671,34.45,56.09,19.00,18.50
15,2023-09-18 13:37:00,3424,20.2392,85.7671,36.83,56.37,33.00,31.00
16,2023-09-20 16:29:00,3424,20.2392,85.7671,32.8,62.89,24.00,23.00
17,2023-09-20 19:23:00,3424,20.2392,85.7671,b,64.63,20.00,19.00
18,2023-11-16 21:47:00,3424,20.2392,85.7671,28.66,54.26,70.17,66.33
19,2023-11-26 00:55:00,3424,20.2392,85.7671,25.35,53.81,178.00,163.00
20,2023-11-26 05:49:00,3424,20.2392,85.7671,31.48,35.54,127.00,117.50
21,2023-11-28 01:51:00,3424,20.2392,85.7671,26.71,52.8,170.00,163.00
22,2023-11-28 10:31:00,3424,20.2392,85.7671,34.23,35.2,143.00,125.00
23,2023-11-28 13:52:00,3424,20.2392,85.7671,31.1,47.54,312.00,298.00
24,2023-12-02 06:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
25,2023-12-02 14:38:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
26,2023-12-15 11:28:00,3424,20.2392,85.7671,29.59,35.08,108.55,99.85
27,2023-12-15 13:39:00,3424,20.2392,85.7671,27.91,43.09,260.45,238.15
28,2023-12-15 19:14:00,3424,20.2392,85.7671,22.44,55.54,219.33,206.83
29,2023-12-29 11:59:00,3424,20.2392,85.7671,30.58,40.9,195.65,181.50

In [5]:
import csv
from datetime import datetime

# Specify the paths for your input and output CSV files
input_csv_path = 'air_raw_data'
pd.read_csv(input_csv_path)
output_csv_path = 'timesorted_data.csv'

# Read data from the input CSV file
with open(input_csv_path, 'r') as file:
    csv_reader = csv.DictReader(file)
    rows = list(csv_reader)

# Convert timestamp strings to datetime objects
for row in rows:
    row['timestamp'] = datetime.strptime(row['timestamp'], '%Y-%m-%d %H:%M:%S')


# Sort the data based on timestamp
sorted_rows = sorted(rows, key=lambda x: x['timestamp'])

# Write the sorted data to a new CSV file
fieldnames = sorted_rows[0].keys()
with open(output_csv_path, 'w', newline='') as file:
    csv_writer = csv.DictWriter(file, fieldnames=fieldnames)

    # Write header
    csv_writer.writeheader()

    # Write sorted rows
    csv_writer.writerows(sorted_rows)

print(f"Sorted data has been written to {output_csv_path}.")

Sorted data has been written to timesorted_data.csv.

In [6]:
input_csv_path = 'timesorted_data.csv'
pd.read_csv(input_csv_path)

,timestamp,device_id,latitude,longitude,temperature,humidity,pm10,pm2_5
0,2023-01-05 02:29:00,3424,20.2392,85.7671,18.4,0,158.00,117.00
1,2023-01-05 15:34:00,3424,20.2392,85.7671,21.9,a,143.00,106.00
2,2023-01-05 17:10:00,3424,20.2392,85.7671,20.9,80.1,123.00,91.00
3,2023-01-12 19:40:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
4,2023-01-12 19:46:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
5,2023-01-15 06:18:00,3424,20.2392,85.7671,28.6,73.1,59.00,44.00
6,2023-01-17 04:13:00,3424,20.2392,85.7671,24.4,132,98.00,NaN
7,2023-01-17 07:27:00,3424,20.2392,85.7671,29.1,81.5,66.00,49.00
8,2023-01-26 03:32:00,3424,20.2392,85.7671,24,85.7,82.00,61.00
9,2023-01-26 11:03:00,3424,20.2392,85.7671,31.5,46.5,48.00,36.00
10,2023-02-01 01:23:00,3424,20.2392,85.7671,22.8,85.4,91.00,68.00
11,2023-03-08 22:32:00,3424,20.2392,85.7671,29.64,53.37,114.00,108.00
12,2023-03-10 05:29:00,3424,20.2392,85.7671,33.59,38.53,152.00,144.00
13,2023-07-25 13:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
14,2023-08-24 23:34:00,3424,20.2392,85.7671,34.45,56.09,19.00,18.50
15,2023-09-18 13:37:00,3424,20.2392,85.7671,36.83,56.37,33.00,31.00
16,2023-09-20 16:29:00,3424,20.2392,85.7671,32.8,62.89,24.00,23.00
17,2023-09-20 19:23:00,3424,20.2392,85.7671,b,64.63,20.00,19.00
18,2023-11-16 21:47:00,3424,20.2392,85.7671,28.66,54.26,70.17,66.33
19,2023-11-26 00:55:00,3424,20.2392,85.7671,25.35,53.81,178.00,163.00
20,2023-11-26 05:49:00,3424,20.2392,85.7671,31.48,35.54,127.00,117.50
21,2023-11-28 01:51:00,3424,20.2392,85.7671,26.71,52.8,170.00,163.00
22,2023-11-28 10:31:00,3424,20.2392,85.7671,34.23,35.2,143.00,125.00
23,2023-11-28 13:52:00,3424,20.2392,85.7671,31.1,47.54,312.00,298.00
24,2023-12-02 06:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
25,2023-12-02 14:38:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
26,2023-12-15 11:28:00,3424,20.2392,85.7671,29.59,35.08,108.55,99.85
27,2023-12-15 13:39:00,3424,20.2392,85.7671,27.91,43.09,260.45,238.15
28,2023-12-15 19:14:00,3424,20.2392,85.7671,22.44,55.54,219.33,206.83
29,2023-12-29 11:59:00,3424,20.2392,85.7671,30.58,40.9,195.65,181.50

In [7]:
timesorted_path = 'timesorted_data.csv'
# timesorted_data = pd.read_csv(cleaned_data_path)
pd.read_csv(timesorted_path)

,timestamp,device_id,latitude,longitude,temperature,humidity,pm10,pm2_5
0,2023-01-05 02:29:00,3424,20.2392,85.7671,18.4,0,158.00,117.00
1,2023-01-05 15:34:00,3424,20.2392,85.7671,21.9,a,143.00,106.00
2,2023-01-05 17:10:00,3424,20.2392,85.7671,20.9,80.1,123.00,91.00
3,2023-01-12 19:40:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
4,2023-01-12 19:46:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
5,2023-01-15 06:18:00,3424,20.2392,85.7671,28.6,73.1,59.00,44.00
6,2023-01-17 04:13:00,3424,20.2392,85.7671,24.4,132,98.00,NaN
7,2023-01-17 07:27:00,3424,20.2392,85.7671,29.1,81.5,66.00,49.00
8,2023-01-26 03:32:00,3424,20.2392,85.7671,24,85.7,82.00,61.00
9,2023-01-26 11:03:00,3424,20.2392,85.7671,31.5,46.5,48.00,36.00
10,2023-02-01 01:23:00,3424,20.2392,85.7671,22.8,85.4,91.00,68.00
11,2023-03-08 22:32:00,3424,20.2392,85.7671,29.64,53.37,114.00,108.00
12,2023-03-10 05:29:00,3424,20.2392,85.7671,33.59,38.53,152.00,144.00
13,2023-07-25 13:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
14,2023-08-24 23:34:00,3424,20.2392,85.7671,34.45,56.09,19.00,18.50
15,2023-09-18 13:37:00,3424,20.2392,85.7671,36.83,56.37,33.00,31.00
16,2023-09-20 16:29:00,3424,20.2392,85.7671,32.8,62.89,24.00,23.00
17,2023-09-20 19:23:00,3424,20.2392,85.7671,b,64.63,20.00,19.00
18,2023-11-16 21:47:00,3424,20.2392,85.7671,28.66,54.26,70.17,66.33
19,2023-11-26 00:55:00,3424,20.2392,85.7671,25.35,53.81,178.00,163.00
20,2023-11-26 05:49:00,3424,20.2392,85.7671,31.48,35.54,127.00,117.50
21,2023-11-28 01:51:00,3424,20.2392,85.7671,26.71,52.8,170.00,163.00
22,2023-11-28 10:31:00,3424,20.2392,85.7671,34.23,35.2,143.00,125.00
23,2023-11-28 13:52:00,3424,20.2392,85.7671,31.1,47.54,312.00,298.00
24,2023-12-02 06:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
25,2023-12-02 14:38:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
26,2023-12-15 11:28:00,3424,20.2392,85.7671,29.59,35.08,108.55,99.85
27,2023-12-15 13:39:00,3424,20.2392,85.7671,27.91,43.09,260.45,238.15
28,2023-12-15 19:14:00,3424,20.2392,85.7671,22.44,55.54,219.33,206.83
29,2023-12-29 11:59:00,3424,20.2392,85.7671,30.58,40.9,195.65,181.50

In [8]:
import pandas as pd

def clean_data(raw_data_path, cleaned_data_path):
    # Read the CSV file into a DataFrame
    df = pd.read_csv(timesorted_path)

    excluded_columns = ['latitude', 'longitude', 'timestamp', 'device_id']
    df = df.dropna(subset=[col for col in df.columns if col not in excluded_columns])

    # Apply pd.to_numeric to specific columns
    for col in [col for col in df.columns if col not in excluded_columns]:
        df[col] = pd.to_numeric(df[col], errors='coerce')

    df = df.dropna(subset=[col for col in df.columns if col not in excluded_columns])

    # Remove rows where any parameter (except excluded columns) is 0
    df = df[(df[[col for col in df.columns if col not in excluded_columns]] != 0).all(axis=1)]

    # Write the cleaned DataFrame to a new CSV file
    df.to_csv(cleaned_data_path, index=False)

# Example usage:
raw_data_path = 'timesorted_data.csv'
cleaned_data_path = 'cleaned_data.csv'
clean_data(raw_data_path, cleaned_data_path)
print(raw_data_path)

timesorted_data.csv

In [9]:
pd.read_csv(cleaned_data_path)

,timestamp,device_id,latitude,longitude,temperature,humidity,pm10,pm2_5
0,2023-01-05 17:10:00,3424,20.2392,85.7671,20.90,80.10,123.00,91.00
1,2023-01-12 19:40:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
2,2023-01-12 19:46:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
3,2023-01-15 06:18:00,3424,20.2392,85.7671,28.60,73.10,59.00,44.00
4,2023-01-17 07:27:00,3424,20.2392,85.7671,29.10,81.50,66.00,49.00
5,2023-01-26 03:32:00,3424,20.2392,85.7671,24.00,85.70,82.00,61.00
6,2023-01-26 11:03:00,3424,20.2392,85.7671,31.50,46.50,48.00,36.00
7,2023-02-01 01:23:00,3424,20.2392,85.7671,22.80,85.40,91.00,68.00
8,2023-03-08 22:32:00,3424,20.2392,85.7671,29.64,53.37,114.00,108.00
9,2023-03-10 05:29:00,3424,20.2392,85.7671,33.59,38.53,152.00,144.00
10,2023-07-25 13:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
11,2023-08-24 23:34:00,3424,20.2392,85.7671,34.45,56.09,19.00,18.50
12,2023-09-18 13:37:00,3424,20.2392,85.7671,36.83,56.37,33.00,31.00
13,2023-09-20 16:29:00,3424,20.2392,85.7671,32.80,62.89,24.00,23.00
14,2023-11-16 21:47:00,3424,20.2392,85.7671,28.66,54.26,70.17,66.33
15,2023-11-26 00:55:00,3424,20.2392,85.7671,25.35,53.81,178.00,163.00
16,2023-11-26 05:49:00,3424,20.2392,85.7671,31.48,35.54,127.00,117.50
17,2023-11-28 01:51:00,3424,20.2392,85.7671,26.71,52.80,170.00,163.00
18,2023-11-28 10:31:00,3424,20.2392,85.7671,34.23,35.20,143.00,125.00
19,2023-11-28 13:52:00,3424,20.2392,85.7671,31.10,47.54,312.00,298.00
20,2023-12-02 06:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
21,2023-12-02 14:38:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
22,2023-12-15 11:28:00,3424,20.2392,85.7671,29.59,35.08,108.55,99.85
23,2023-12-15 13:39:00,3424,20.2392,85.7671,27.91,43.09,260.45,238.15
24,2023-12-15 19:14:00,3424,20.2392,85.7671,22.44,55.54,219.33,206.83
25,2023-12-29 11:59:00,3424,20.2392,85.7671,30.58,40.90,195.65,181.50

In [11]:
import pandas as pd

# Read the dataset from a CSV file
file_path = 'cleaned_data.csv'
df = pd.read_csv(file_path, parse_dates=['timestamp'])

# Calculate time differences between consecutive timestamps
df['time_diff'] = df['timestamp'].diff()

# Filter rows based on conditions
mask = (df['time_diff'] > pd.Timedelta(minutes=5))
df_filtered = df[mask | mask.shift(-1)]

# Check and delete rows with the same parameter value
to_drop = set()
for i in range(len(df_filtered) - 1):
    if (df_filtered.iloc[i]['temperature'] == df_filtered.iloc[i + 1]['temperature'] or
            df_filtered.iloc[i]['humidity'] == df_filtered.iloc[i + 1]['humidity'] or
            df_filtered.iloc[i]['pm10'] == df_filtered.iloc[i + 1]['pm10'] or
            df_filtered.iloc[i]['pm2_5'] == df_filtered.iloc[i + 1]['pm2_5']):
        to_drop.add(i)
        to_drop.add(i + 1)

# Drop the rows with duplicate parameter values
df_filtered = df_filtered.drop(list(to_drop))

# Drop the 'time_diff' column as it is no longer needed
df_filtered = df_filtered.drop(columns=['time_diff'])

# Write the filtered data to a new CSV file
df_filtered.to_csv('filtered_data.csv', index=False)

In [12]:
pd.read_csv('filtered_data.csv')

,timestamp,device_id,latitude,longitude,temperature,humidity,pm10,pm2_5
0,2023-01-05 17:10:00,3424,20.2392,85.7671,20.90,80.10,123.00,91.00
1,2023-01-15 06:18:00,3424,20.2392,85.7671,28.60,73.10,59.00,44.00
2,2023-01-17 07:27:00,3424,20.2392,85.7671,29.10,81.50,66.00,49.00
3,2023-01-26 03:32:00,3424,20.2392,85.7671,24.00,85.70,82.00,61.00
4,2023-01-26 11:03:00,3424,20.2392,85.7671,31.50,46.50,48.00,36.00
5,2023-02-01 01:23:00,3424,20.2392,85.7671,22.80,85.40,91.00,68.00
6,2023-03-08 22:32:00,3424,20.2392,85.7671,29.64,53.37,114.00,108.00
7,2023-03-10 05:29:00,3424,20.2392,85.7671,33.59,38.53,152.00,144.00
8,2023-07-25 13:55:00,3424,20.2392,85.7671,33.06,40.61,135.00,128.00
9,2023-08-24 23:34:00,3424,20.2392,85.7671,34.45,56.09,19.00,18.50
10,2023-09-18 13:37:00,3424,20.2392,85.7671,36.83,56.37,33.00,31.00
11,2023-09-20 16:29:00,3424,20.2392,85.7671,32.80,62.89,24.00,23.00
12,2023-11-16 21:47:00,3424,20.2392,85.7671,28.66,54.26,70.17,66.33
13,2023-11-26 00:55:00,3424,20.2392,85.7671,25.35,53.81,178.00,163.00
14,2023-11-26 05:49:00,3424,20.2392,85.7671,31.48,35.54,127.00,117.50
15,2023-11-28 01:51:00,3424,20.2392,85.7671,26.71,52.80,170.00,163.00
16,2023-11-28 10:31:00,3424,20.2392,85.7671,34.23,35.20,143.00,125.00
17,2023-11-28 13:52:00,3424,20.2392,85.7671,31.10,47.54,312.00,298.00
18,2023-12-15 11:28:00,3424,20.2392,85.7671,29.59,35.08,108.55,99.85
19,2023-12-15 13:39:00,3424,20.2392,85.7671,27.91,43.09,260.45,238.15
20,2023-12-15 19:14:00,3424,20.2392,85.7671,22.44,55.54,219.33,206.83
21,2023-12-29 11:59:00,3424,20.2392,85.7671,30.58,40.90,195.65,181.50